config/routes.rb
Odot::Application.routes.draw do
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  validates :content, presence: true,
                      length: { minimum: 2 }

  scope :complete, -> { where("completed_at is not null") }
  scope :incomplete, -> { where(completed_at: nil) }

  def completed?
    !completed_at.blank?
  end

end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :require_user
  before_action :find_todo_list

  def index

  end

  def new
    @todo_item = @todo_list.todo_items.new
  end

  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)
    if @todo_item.save
      flash[:success] = "Added todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "There was a problem adding that todo list item."
      render action: :new
    end
  end

  def edit
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def update
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = "Saved todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "That todo item could not be saved."
      render action: :edit
    end
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Todo list item was deleted."
    else
      flash[:error] = "Todo list item could not be deleted. Ha ha!"
    end
    redirect_to todo_list_todo_items_path
  end

  def complete
    @todo_item = @todo_list.todo_items.find(params[:id])
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to todo_list_todo_items_path, notice: "Todo item marked as complete."
  end

  def url_options
    { todo_list_id: params[:todo_list_id] }.merge(super)
  end

  private

  def find_todo_list
    @todo_list = current_user.todo_lists.find(params[:todo_list_id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<% if @todo_item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

    <ul>
    <% @todo_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form.label :content %>
<%= form.text_field :content %>

<%= form.submit "Save" %>

app/views/todo_items/edit.html.erb
<h1><%= @todo_list.title %> - Editing Todo List Item</h1>

<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %>

app/views/todo_items/index.html.erb
<h1><%= @todo_list.title %></h1>

<table class="todo_items">
  <thead>
    <tr>
      <th width="25%">Completed?</th>
      <th width="65%">Content</th>
      <th width="10%">Functions</th>
    </tr>
  </thead>
  <tbody>
    <% @todo_list.todo_items.each do |todo_item| %>
      <tr id="<%= dom_id(todo_item) %>">
        <td>
          <% if todo_item.completed? %>
            <%= todo_item.completed_at %>
          <% else %>
          <%= link_to "Mark Complete", complete_todo_list_todo_item_path(todo_item), method: :patch %>
          <% end %>
        </td>
        <td><%= todo_item.content %></td>
        <td>
          <%= link_to "Edit", edit_todo_list_todo_item_path(todo_item) %>
          <%= link_to "Delete", todo_list_todo_item_path(todo_item), method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to "New Todo Item", new_todo_list_todo_item_path %>
</p>

app/views/todo_items/new.html.erb
<h1><%= @todo_list.title %> - Add Todo List Item</h1>

<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %>